main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('tambah_kegiatan/', views.tambah_kegiatan, name='tambah_kegiatan'),
    path('tambah_orang/<int:id>/', views.tambah_orang, name='tambah_orang'),
]

story/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/models.py
from django.db import models

# Create your models here.

class Kegiatan(models.Model):
    nama_kegiatan = models.CharField("Nama", max_length = 50)
    deskripsi = models.TextField("Deskripsi", max_length = 100)

    def __str__(self):
        return self.nama_kegiatan

class Person(models.Model):
    nama_orang = models.CharField("Nama", max_length = 50)
    kegiatan = models.ForeignKey("Kegiatan", on_delete = models.CASCADE)

    def __str__(self):
        return self.nama_orang

main/forms.py
from django import forms
from .models import Kegiatan, Person
from django.forms import ModelForm

##Create your forms here

class FormKegiatan(ModelForm):
    class Meta:
        model = Kegiatan
        fields = '__all__'

class FormPerson(ModelForm):
    class Meta:
        model = Person
        fields = ['nama_orang']
        

main/views.py
from django.shortcuts import render, redirect
from .models import Kegiatan, Person
from .forms import FormKegiatan, FormPerson

def home(request):

    person = Person.objects.all()
    kegiatan = Kegiatan.objects.all()
    context = {'person' : person, 'kegiatan' : kegiatan}  

    return render(request, 'main/home.html', context)


def tambah_kegiatan(request):

    if request.method == "POST":
        form = FormKegiatan(request.POST)

        if form.is_valid():
            form.save()
            return redirect("main:home")

    else:
        form = FormKegiatan

    context = {'form' : form}            
    return render(request, 'main/tambah_kegiatan.html', context)

def tambah_orang(request, id):

    if request.method == "POST":
        form = FormPerson(request.POST)

        form = Person(kegiatan = Kegiatan.objects.get(id=id), nama_orang = form.data['nama_orang'])
        form.save()
        return redirect('main:home')

    else:
        form = FormPerson
        
    context = {'form' : form}
    return render(request, 'main/tambah_orang.html', context)

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Home</title>
{% endblock meta %}

{% block content %}
	<div class="container mt-5">
		{% for x in kegiatan %}
		<table class="table table-borderless text-center">
			<tr>
				<th>Kegiatan</th>
			</tr>
			<tr>
				<td>{{x.nama_kegiatan}}</td>
			</tr> 
			<tr>
				<th>Deskripsi</th>
			</tr>
			<tr>
				<td>{{x.deskripsi}}</td>
			</tr>     
			<tr>
				<th>Peserta</th>
			</tr> 
			{% for y in person %}
				{% if y.kegiatan == x %} 
			<tr>
				<td>{{y.nama_orang}}</td>
			</tr>
			{% endif %}
				{% endfor %}
		</table>

		<div class="row">
			<div class="col text-center">
						<a class="btn btn-outline-success btn-block" href="{% url 'main:tambah_orang' x.id %}">Tambah Peserta</a>
			</div>
		</div>
	{% endfor %}
	</div>
{% endblock content %}

main/templates/main/tambah_kegiatan.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Form Kegiatan</title>
{% endblock meta %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col text-center">
            <h2>Form Kegiatan</h2>
        </div>
    </div>

    <div class="row mt-5">
        <form action="/tambah_kegiatan/" method="POST">
            {% csrf_token %}
            <table>
                {{form.as_table}}
            </table>
            <input type="submit" value="Submit">
        </form>
    </div>
</div>
{% endblock content %}

main/templates/main/tambah_orang.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Form Peserta</title>
{% endblock meta %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col text-center">
            <h2>Form Peserta</h2>
        </div>
    </div>

    <div class="row mt-5">
        <form action="" method="POST">
            {% csrf_token %}
            <table>
                {{form.as_table}}
            </table>
            <input type="submit" value="Submit">
        </form>
    </div>
</div>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

 <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Font -->
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <!-- CSS AING -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block meta %}
    {% endblock meta %}
  </head>
  <body class="mt-5">
    <!-- <h1>Hello, world!</h1> -->
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
        <a class="navbar-brand" href="#home">Ghifari</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav ml-auto">
            <!-- <a class="nav-item nav-link page-scroll" href="#home">Home <span class="sr-only">(current)</span></a> -->
            <a class="nav-item nav-link" href="{% url 'main:home' %}">Home</a>
            <a class="nav-item nav-link" href="{% url 'main:tambah_kegiatan' %}">Tambah Kegiatan</a>
            <!-- <a class="nav-item nav-link" href="tambah_orang">Tambah Peserta</a> -->
            <!-- <a class="nav-item nav-link" href="story1" target="_blank">Story 1</a> -->
          </div>
        </div>
        </div>
      </nav>
      {% block content %}
      {% endblock content %}

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
  </body>
</html>